### ISSUE TITLE
Missing shared libraries: libpoppler.so.66

### ISSUE THREAD

**Issue by honnorat** [conda-forge/ncl-feedstock#25] opened 2017-11-27 09:51 UTC
Hi, since last update on linux, I am no longer able to launch ncl. I have the following error message:

`ncl: error while loading shared libraries: libpoppler.so.66: cannot open shared object file: No such file or directory`

I installed ncl in its own python3 environment:
```bash
$ conda create -n ncl python=3 ncl
[...]
$ source activate ncl
$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.29
       conda is private : False
      conda-env version : 4.3.29
    conda-build version : 2.1.17
         python version : 3.6.3.final.0
       requests version : 2.18.4
[...]
$ ldd $CONDA_PREFIX/bin/ncl | grep poppler
        libpoppler.so.66 => not found
$ conda list |grep -E "(ncl|poppler)"
# packages in environment at /home/honnorat/usr/conda/envs/ncl:
ncl                       6.4.0           blas_openblas_6  [blas_openblas]  conda-forge
poppler                   0.61.1                        2    conda-forge
poppler-data              0.4.8                         0    conda-forge
```

**Comment by ocefpaf** [comment] 2017-11-27 13:02
We rebuilt `gdal` with latest `poppler` and the previous build was unpinned, causing this error. You can try to install the older version of `poppler` to see if that downloads the older version of `gdal`, but a real fix is to rebuild `ncl` with the new pnning scheme. See #24

**Comment by ocefpaf** [comment] 2017-11-27 13:13
BTW, forcing the old `poppler` (and `xerces-c`, another one we updated the pinning) did the trick for me:

```
conda install poppler=0.52.0 xerces-c=3.1.4
```

That is a workaround until we fix #24

**Comment by honnorat** [comment] 2017-11-27 16:20
Thanks ! It did the trick for me too.

Btw, I now have the following warning when I launch ncl:

`ncl: /home/honnorat/usr/conda/envs/ncl/bin/../lib/./libuuid.so.1: no version information available (required by /home/honnorat/usr/conda/envs/ncl/bin/../lib/./libdapserver.so.7)`

Anything related to a bad rebuild ?

**Comment by ocefpaf** [comment] 2017-11-27 16:30
> Anything related to a bad rebuild ?

Probably. The only real fix is to rebuild `ncl` :unamused:

**Comment by ocefpaf** [comment] 2018-01-31 20:26
Should be fixed by #27

Please re-open if you are still experiencing issues.

**Closed by ocefpaf** 2018-01-31 20:26 UTC

**Comment by cehbrecht** [comment] 2018-02-07 15:32
I tried the new ncl package ... but I still have troubles with poppler:

```
$ conda create -n ncl -c conda-forge -c defaults ncl
$ source activate ncl
$ ncl -V
ncl: error while loading shared libraries: libpoppler.so.71: cannot open shared object file: No such file or directory

$ conda search poppler
poppler                 0.52.0                        1  conda-forge     
                             0.52.0                        2  conda-forge     
                             0.52.0                        3  conda-forge     
                             0.52.0                        4  conda-forge     
                             0.61.1                        0  conda-forge     
                             0.61.1                        1  conda-forge     
                             0.61.1                        2  conda-forge     
                          *  0.61.1                        3  conda-forge     
                             0.60.1               hc909a00_0  defaults    
``` 

I have  tested it on LinuxMint 18.3 ... but tried also Ubuntu with Docker. It works on macOS ... but macOS does not have the poppler dependency.

**Comment by khallock** [comment] 2018-02-07 18:05
Hi @cehbrecht,

I was able to reproduce this issue, but _only_ when my root conda environment uses Python 3 and has `conda=4.3.30` installed. Using Python 2 with `conda=4.3.30` seemed to get NCL working properly, and upgrading my Python 3 `conda` package with `conda update --all` (which installed `conda=4.4.8`) and rerunning the `conda create ...` command also worked.

If you would prefer to not upgrade `conda`, a workaround would be to explicitly install `libgdal=2.2.3` when creating your environment:
```conda create -n ncl -c conda-forge -c defaults ncl libgdal=2.2.3```

I hope this helps!

**Comment by cehbrecht** [comment] 2018-02-08 09:53
@khallock 
Thanks :) pinning `libgdal` works for me.

**Comment by prativadas** [comment] 2019-03-16 17:14
I was having the same issue. so i opened anaconda navigator and go to the env. then in the channels, you can see default and conda-forge so you can delete conda-forge. then again install gdal, poppler. both will be available on default channel. this works for me

**Comment by ocefpaf** [comment] 2019-03-17 12:39
> I was having the same issue. so i opened anaconda navigator and go to the env. then in the channels, you can see default and conda-forge so you can delete conda-forge. then again install gdal, poppler. both will be available on default channel. this works for me

@prativadas you probably did not install `ncl` then, b/c that is not available on `defaults`. Please don't post solutions that are not pertinent to the issue in question. Specially a closed/solved one.
